title: Polystruct's Creative Minecraft
email: nickname-at-protonmail-dot-com
description: >-
  A collection of creative ideas and methods for developing worlds.
  Contains not only creative ideas for vanilla minecraft, but also
  WorldPainter, WorldEdit and possibly other tools and mods.
baseurl: "/creative"
url: "https://polystruct.github.io"
twitter_username: nope
github_username:  polystruct

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

#plugins:
#  - jekyll-remote-theme

# Site setting: Search
search_enabled: true

# Charting
mermaid:
  version: "9.2.2"
